apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: nexchat
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteMany   # Multiple backend replicas share uploads storage
  resources:
    requests:
      storage: 20Gi
