apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus          # Must match "uid" in dashboard JSON panels
    access: proxy
    url: http://nexchat-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST
